name: pshondation
description:
version: 0.1.1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  intl: any
  meta: any
  logging: any
  logger: any

  cancellation_token: any
  
  synchronized: any