name: true_core
description:
version: 0.0.8
homepage:
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  # DateFormat
  intl: any
  meta: any
  logging: any
  logger: any

  synchronized: any